# Generated by Django 5.2.6 on 2025-09-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
